// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

void* winrt_make_Hot3dxBlankApp2_MainPage()
{
    return winrt::detach_abi(winrt::make<winrt::Hot3dxBlankApp2::factory_implementation::MainPage>());
}
WINRT_EXPORT namespace winrt::Hot3dxBlankApp2
{
    MainPage::MainPage() :
        MainPage(make<Hot3dxBlankApp2::implementation::MainPage>())
    {
    }
    hstring MainPage::FEATURE_NAME()
    {
        return Hot3dxBlankApp2::implementation::MainPage::FEATURE_NAME();
    }
    winrt::Windows::Foundation::Collections::IVector<winrt::Hot3dxBlankApp2::ScenarioInfo> MainPage::scenarios2()
    {
        return Hot3dxBlankApp2::implementation::MainPage::scenarios2();
    }
    winrt::Hot3dxBlankApp2::MainPage MainPage::Current()
    {
        return Hot3dxBlankApp2::implementation::MainPage::Current();
    }
}
