// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

void* winrt_make_Hot3dxBlankApp2_Scenario2()
{
    return winrt::detach_abi(winrt::make<winrt::Hot3dxBlankApp2::factory_implementation::Scenario2>());
}
WINRT_EXPORT namespace winrt::Hot3dxBlankApp2
{
    Scenario2::Scenario2() :
        Scenario2(make<Hot3dxBlankApp2::implementation::Scenario2>())
    {
    }
}
