//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once


namespace winrt::Hot3dxBlankApp2::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct Scenario1T : public ::winrt::Hot3dxBlankApp2::implementation::Scenario1_base<D,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector2,
        I...>
    {
        using base_type = typename Scenario1T::base_type;
        using base_type::base_type;
        using class_type = typename Scenario1T::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Windows::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Windows::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Windows::UI::Xaml::Controls::TextBlock textBlockScenario1()
        {
            return _textBlockScenario1;
        }
        void textBlockScenario1(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _textBlockScenario1 = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock textBlockPlaceHolder()
        {
            return _textBlockPlaceHolder;
        }
        void textBlockPlaceHolder(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _textBlockPlaceHolder = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct Scenario1_obj1_Bindings;

        ::winrt::Windows::UI::Xaml::Controls::TextBlock _textBlockScenario1{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _textBlockPlaceHolder{nullptr};
    };
}

